/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AppMetadata = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAppMetadata' : IDL.Func([], [AppMetadata], ['query']),
  'updateAppMetadata' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AppMetadata = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
  });
  
  return IDL.Service({
    'getAppMetadata' : IDL.Func([], [AppMetadata], ['query']),
    'updateAppMetadata' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };